# Generated by Django 2.2.4 on 2019-09-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20190901_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarymodel',
            options={'ordering': ['-timestamp']},
        ),
    ]
