# Generated by Django 2.2.4 on 2019-09-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20190902_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymodel',
            name='adventure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
